/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import tools.Util;
import java.util.List;
import bean.LmpProduto;
import bean.LmpVendasItens;
import dao.LmpProdutoDao;

/**
 *
 * @author laura
 */
public class LmpJDlgVendasItens extends javax.swing.JDialog {
    LmpJDlgVendas lmpJDlgVendas;
    
    private boolean escuro = false;

    /**
     * Creates new form LmpJDlgVendasItens
     */
    public LmpJDlgVendasItens(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Vendas Itens");
        setLocationRelativeTo(null);
         lmpjTxtQuantidade.setText("1");
        LmpProdutoDao lmpProdutoDao = new LmpProdutoDao();
        List lista = (List) lmpProdutoDao.listAll();
        for (Object object : lista) {
            lmpjCboProduto.addItem((LmpProduto) object);
        }
        Util.habilitar(false, lmpjTxtValorUni, lmpjTxtTotal);
       
    }
    
    public void setTelaAnterior(LmpJDlgVendas lmpJDlgVendas) {
        this.lmpJDlgVendas = lmpJDlgVendas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lmpBtnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lmpjCboProduto = new javax.swing.JComboBox<LmpProduto>();
        jLabel2 = new javax.swing.JLabel();
        lmpjTxtQuantidade = new javax.swing.JTextField();
        lmpjTxtValorUni = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lmpjTxtTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lmpBtnOk = new javax.swing.JButton();
        jBtnModo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lmpBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        lmpBtnCancelar.setText("Cancelar");
        lmpBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lmpBtnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Produtos");

        lmpjCboProduto.setModel(new javax.swing.DefaultComboBoxModel<LmpProduto>());
        lmpjCboProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lmpjCboProdutoActionPerformed(evt);
            }
        });
        lmpjCboProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lmpjCboProdutoKeyReleased(evt);
            }
        });

        jLabel2.setText("Quantidade");

        jLabel3.setText("Valor Unitário");

        jLabel4.setText("Total");

        lmpBtnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        lmpBtnOk.setText("OK");
        lmpBtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lmpBtnOkActionPerformed(evt);
            }
        });

        jBtnModo.setText("🌙 Modo Escuro");
        jBtnModo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnModoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lmpjTxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lmpjTxtValorUni, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lmpjTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lmpjCboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(23, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(lmpBtnOk)
                        .addGap(40, 40, 40)
                        .addComponent(lmpBtnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jBtnModo)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lmpjCboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lmpjTxtValorUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lmpjTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lmpjTxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lmpBtnOk)
                    .addComponent(lmpBtnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jBtnModo)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lmpBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lmpBtnCancelarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_lmpBtnCancelarActionPerformed

    private void lmpBtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lmpBtnOkActionPerformed
        // TODO add your handling code here:
        LmpVendasItens lmpVendasItens = new LmpVendasItens();
        lmpVendasItens.setLmpProduto((LmpProduto) lmpjCboProduto.getSelectedItem());
        lmpVendasItens.setLmpQuantidade(Util.strToInt(lmpjTxtQuantidade.getText()) );
        lmpVendasItens.setLmpPrecoUnitario(Util.strToDouble(lmpjTxtValorUni.getText()) );                
        lmpJDlgVendas.controllerVendItens.addBean(lmpVendasItens);
        setVisible(false);
    }//GEN-LAST:event_lmpBtnOkActionPerformed

    private void jBtnModoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnModoActionPerformed
        // TODO add your handling code here:
        tools.TemaUtil.alternarTema(this);
        escuro = !escuro;
        jBtnModo.setText(escuro ? "☀ Modo Claro" : "🌙 Modo Escuro");
    }//GEN-LAST:event_jBtnModoActionPerformed

    private void lmpjCboProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lmpjCboProdutoKeyReleased
        // TODO add your handling code here:
        if(lmpjTxtQuantidade.getText().isEmpty() == false){
        LmpProduto lmpProduto = (LmpProduto) lmpjCboProduto.getSelectedItem();
        int quant = Util.strToInt(lmpjTxtQuantidade.getText());
        double preco = Util.strToDouble(lmpProduto.getLmpPreco());
        lmpjTxtTotal.setText(Util.doubleToStr( quant * preco));
       } else {
           Util.limpar(lmpjTxtTotal);
       }
    }//GEN-LAST:event_lmpjCboProdutoKeyReleased

    private void lmpjCboProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lmpjCboProdutoActionPerformed
        // TODO add your handling code here:
        LmpProduto lmpProduto = (LmpProduto) lmpjCboProduto.getSelectedItem();
        lmpjTxtValorUni.setText(lmpProduto.getLmpPreco());
        int quant = Util.strToInt(lmpjTxtQuantidade.getText());
         double preco = Util.strToDouble(lmpProduto.getLmpPreco());
        lmpjTxtTotal.setText(Util.doubleToStr( quant * preco));
    }//GEN-LAST:event_lmpjCboProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LmpJDlgVendasItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LmpJDlgVendasItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LmpJDlgVendasItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LmpJDlgVendasItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LmpJDlgVendasItens dialog = new LmpJDlgVendasItens(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnModo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton lmpBtnCancelar;
    private javax.swing.JButton lmpBtnOk;
    private transient javax.swing.JComboBox<LmpProduto> lmpjCboProduto;
    private javax.swing.JTextField lmpjTxtQuantidade;
    private javax.swing.JTextField lmpjTxtTotal;
    private javax.swing.JTextField lmpjTxtValorUni;
    // End of variables declaration//GEN-END:variables
}
