package bean;
// Generated 13/10/2025 22:36:20 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LmpClientes generated by hbm2java
 */
@Entity
@Table(name="lmp_clientes"
    ,catalog="db_laura_peixoto"
)
public class LmpClientes  implements java.io.Serializable {


     private int lmpIdCodigo;
     private String lmpNome;
     private String lmpCpf;
     private String lmpEmail;
     private String lmpTelefone;
     private String lmpEndereco;
     private Date lmpDataCadastro;
     private Date lmpDataNascimento;
     private String lmpNacionalidade;
     private String lmpSenha;
     private String lmpProfissao;
     private String lmpPais;
     private String lmpEstado;
     private String lmpSexo;
     private String lmpAtivo;

    public LmpClientes() {
    }

	
    public LmpClientes(int lmpIdCodigo, String lmpNome, String lmpCpf, String lmpEmail, String lmpTelefone, String lmpEndereco, String lmpNacionalidade, String lmpSenha, String lmpProfissao, String lmpPais, String lmpEstado, String lmpSexo, String lmpAtivo) {
        this.lmpIdCodigo = lmpIdCodigo;
        this.lmpNome = lmpNome;
        this.lmpCpf = lmpCpf;
        this.lmpEmail = lmpEmail;
        this.lmpTelefone = lmpTelefone;
        this.lmpEndereco = lmpEndereco;
        this.lmpNacionalidade = lmpNacionalidade;
        this.lmpSenha = lmpSenha;
        this.lmpProfissao = lmpProfissao;
        this.lmpPais = lmpPais;
        this.lmpEstado = lmpEstado;
        this.lmpSexo = lmpSexo;
        this.lmpAtivo = lmpAtivo;
    }
    public LmpClientes(int lmpIdCodigo, String lmpNome, String lmpCpf, String lmpEmail, String lmpTelefone, String lmpEndereco, Date lmpDataCadastro, Date lmpDataNascimento, String lmpNacionalidade, String lmpSenha, String lmpProfissao, String lmpPais, String lmpEstado, String lmpSexo, String lmpAtivo) {
       this.lmpIdCodigo = lmpIdCodigo;
       this.lmpNome = lmpNome;
       this.lmpCpf = lmpCpf;
       this.lmpEmail = lmpEmail;
       this.lmpTelefone = lmpTelefone;
       this.lmpEndereco = lmpEndereco;
       this.lmpDataCadastro = lmpDataCadastro;
       this.lmpDataNascimento = lmpDataNascimento;
       this.lmpNacionalidade = lmpNacionalidade;
       this.lmpSenha = lmpSenha;
       this.lmpProfissao = lmpProfissao;
       this.lmpPais = lmpPais;
       this.lmpEstado = lmpEstado;
       this.lmpSexo = lmpSexo;
       this.lmpAtivo = lmpAtivo;
    }
   
     @Id 

    
    @Column(name="lmp_idCodigo", unique=true, nullable=false)
    public int getLmpIdCodigo() {
        return this.lmpIdCodigo;
    }
    
    public void setLmpIdCodigo(int lmpIdCodigo) {
        this.lmpIdCodigo = lmpIdCodigo;
    }

    
    @Column(name="lmp_nome", nullable=false, length=100)
    public String getLmpNome() {
        return this.lmpNome;
    }
    
    public void setLmpNome(String lmpNome) {
        this.lmpNome = lmpNome;
    }

    
    @Column(name="lmp_cpf", nullable=false, length=14)
    public String getLmpCpf() {
        return this.lmpCpf;
    }
    
    public void setLmpCpf(String lmpCpf) {
        this.lmpCpf = lmpCpf;
    }

    
    @Column(name="lmp_email", nullable=false, length=80)
    public String getLmpEmail() {
        return this.lmpEmail;
    }
    
    public void setLmpEmail(String lmpEmail) {
        this.lmpEmail = lmpEmail;
    }

    
    @Column(name="lmp_telefone", nullable=false, length=15)
    public String getLmpTelefone() {
        return this.lmpTelefone;
    }
    
    public void setLmpTelefone(String lmpTelefone) {
        this.lmpTelefone = lmpTelefone;
    }

    
    @Column(name="lmp_endereco", nullable=false, length=200)
    public String getLmpEndereco() {
        return this.lmpEndereco;
    }
    
    public void setLmpEndereco(String lmpEndereco) {
        this.lmpEndereco = lmpEndereco;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="lmp_dataCadastro", length=10)
    public Date getLmpDataCadastro() {
        return this.lmpDataCadastro;
    }
    
    public void setLmpDataCadastro(Date lmpDataCadastro) {
        this.lmpDataCadastro = lmpDataCadastro;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="lmp_dataNascimento", length=10)
    public Date getLmpDataNascimento() {
        return this.lmpDataNascimento;
    }
    
    public void setLmpDataNascimento(Date lmpDataNascimento) {
        this.lmpDataNascimento = lmpDataNascimento;
    }

    
    @Column(name="lmp_nacionalidade", nullable=false, length=50)
    public String getLmpNacionalidade() {
        return this.lmpNacionalidade;
    }
    
    public void setLmpNacionalidade(String lmpNacionalidade) {
        this.lmpNacionalidade = lmpNacionalidade;
    }

    
    @Column(name="lmp_senha", nullable=false, length=50)
    public String getLmpSenha() {
        return this.lmpSenha;
    }
    
    public void setLmpSenha(String lmpSenha) {
        this.lmpSenha = lmpSenha;
    }

    
    @Column(name="lmp_profissao", nullable=false, length=100)
    public String getLmpProfissao() {
        return this.lmpProfissao;
    }
    
    public void setLmpProfissao(String lmpProfissao) {
        this.lmpProfissao = lmpProfissao;
    }

    
    @Column(name="lmp_pais", nullable=false, length=50)
    public String getLmpPais() {
        return this.lmpPais;
    }
    
    public void setLmpPais(String lmpPais) {
        this.lmpPais = lmpPais;
    }

    
    @Column(name="lmp_estado", nullable=false, length=2)
    public String getLmpEstado() {
        return this.lmpEstado;
    }
    
    public void setLmpEstado(String lmpEstado) {
        this.lmpEstado = lmpEstado;
    }

    
    @Column(name="lmp_sexo", nullable=false, length=1)
    public String getLmpSexo() {
        return this.lmpSexo;
    }
    
    public void setLmpSexo(String lmpSexo) {
        this.lmpSexo = lmpSexo;
    }

    
    @Column(name="lmp_ativo", nullable=false, length=1)
    public String getLmpAtivo() {
        return this.lmpAtivo;
    }
    
    public void setLmpAtivo(String lmpAtivo) {
        this.lmpAtivo = lmpAtivo;
    }


    @Override
    public String toString() {
        return this.lmpNome;
    }

    
}


