package bean;
// Generated 13/10/2025 22:36:20 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LmpFuncionarios generated by hbm2java
 */
@Entity
@Table(name="lmp_funcionarios"
    ,catalog="db_laura_peixoto"
)
public class LmpFuncionarios  implements java.io.Serializable {


     private int lmpIdFuncionario;
     private String lmpNome;
     private String lmpCpf;
     private String lmpEmail;
     private String lmpTelefone;
     private String lmpCargo;
     private Date lmpDataAdmissao;

    public LmpFuncionarios() {
    }

	
    public LmpFuncionarios(int lmpIdFuncionario, String lmpNome, String lmpCpf, String lmpEmail, String lmpTelefone, String lmpCargo) {
        this.lmpIdFuncionario = lmpIdFuncionario;
        this.lmpNome = lmpNome;
        this.lmpCpf = lmpCpf;
        this.lmpEmail = lmpEmail;
        this.lmpTelefone = lmpTelefone;
        this.lmpCargo = lmpCargo;
    }
    public LmpFuncionarios(int lmpIdFuncionario, String lmpNome, String lmpCpf, String lmpEmail, String lmpTelefone, String lmpCargo, Date lmpDataAdmissao) {
       this.lmpIdFuncionario = lmpIdFuncionario;
       this.lmpNome = lmpNome;
       this.lmpCpf = lmpCpf;
       this.lmpEmail = lmpEmail;
       this.lmpTelefone = lmpTelefone;
       this.lmpCargo = lmpCargo;
       this.lmpDataAdmissao = lmpDataAdmissao;
    }
   
     @Id 

    
    @Column(name="lmp_idFuncionario", unique=true, nullable=false)
    public int getLmpIdFuncionario() {
        return this.lmpIdFuncionario;
    }
    
    public void setLmpIdFuncionario(int lmpIdFuncionario) {
        this.lmpIdFuncionario = lmpIdFuncionario;
    }

    
    @Column(name="lmp_nome", nullable=false, length=100)
    public String getLmpNome() {
        return this.lmpNome;
    }
    
    public void setLmpNome(String lmpNome) {
        this.lmpNome = lmpNome;
    }

    
    @Column(name="lmp_CPF", nullable=false, length=14)
    public String getLmpCpf() {
        return this.lmpCpf;
    }
    
    public void setLmpCpf(String lmpCpf) {
        this.lmpCpf = lmpCpf;
    }

    
    @Column(name="lmp_email", nullable=false, length=80)
    public String getLmpEmail() {
        return this.lmpEmail;
    }
    
    public void setLmpEmail(String lmpEmail) {
        this.lmpEmail = lmpEmail;
    }

    
    @Column(name="lmp_telefone", nullable=false, length=15)
    public String getLmpTelefone() {
        return this.lmpTelefone;
    }
    
    public void setLmpTelefone(String lmpTelefone) {
        this.lmpTelefone = lmpTelefone;
    }

    
    @Column(name="lmp_Cargo", nullable=false, length=50)
    public String getLmpCargo() {
        return this.lmpCargo;
    }
    
    public void setLmpCargo(String lmpCargo) {
        this.lmpCargo = lmpCargo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="lmp_dataAdmissao", length=10)
    public Date getLmpDataAdmissao() {
        return this.lmpDataAdmissao;
    }
    
    public void setLmpDataAdmissao(Date lmpDataAdmissao) {
        this.lmpDataAdmissao = lmpDataAdmissao;
    }

     @Override
    public String toString() {
        return this.lmpNome;
    }


}


