package bean;
// Generated 13/10/2025 22:36:20 by Hibernate Tools 4.3.1


import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LmpProduto generated by hbm2java
 */
@Entity
@Table(name="lmp_produto"
    ,catalog="db_laura_peixoto"
)
public class LmpProduto  implements java.io.Serializable {


     private int lmpIdCodigoProduto;
     private String lmpNome;
     private String lmpDescricao;
     private String lmpPreco;
     private String lmpCategoria;
     private String lmpTamanho;
     private String lmpAtivo;
    

    public LmpProduto() {
    }

	
    public LmpProduto(int lmpIdCodigoProduto, String lmpDescricao, String lmpPreco, String lmpCategoria, String lmpAtivo) {
        this.lmpIdCodigoProduto = lmpIdCodigoProduto;
        this.lmpDescricao = lmpDescricao;
        this.lmpPreco = lmpPreco;
        this.lmpCategoria = lmpCategoria;
        this.lmpAtivo = lmpAtivo;
    }
    public LmpProduto(int lmpIdCodigoProduto, String lmpNome, String lmpDescricao, String lmpPreco, String lmpCategoria, String lmpTamanho, String lmpAtivo, Set lmpVendasItenses) {
       this.lmpIdCodigoProduto = lmpIdCodigoProduto;
       this.lmpNome = lmpNome;
       this.lmpDescricao = lmpDescricao;
       this.lmpPreco = lmpPreco;
       this.lmpCategoria = lmpCategoria;
       this.lmpTamanho = lmpTamanho;
       this.lmpAtivo = lmpAtivo;
    }
   
     @Id 

    
    @Column(name="lmp_idCodigoProduto", unique=true, nullable=false)
    public int getLmpIdCodigoProduto() {
        return this.lmpIdCodigoProduto;
    }
    
    public void setLmpIdCodigoProduto(int lmpIdCodigoProduto) {
        this.lmpIdCodigoProduto = lmpIdCodigoProduto;
    }

    
    @Column(name="lmp_nome", length=100)
    public String getLmpNome() {
        return this.lmpNome;
    }
    
    public void setLmpNome(String lmpNome) {
        this.lmpNome = lmpNome;
    }

    
    @Column(name="lmp_descricao", nullable=false, length=100)
    public String getLmpDescricao() {
        return this.lmpDescricao;
    }
    
    public void setLmpDescricao(String lmpDescricao) {
        this.lmpDescricao = lmpDescricao;
    }

    
    @Column(name="lmp_preco", nullable=false, length=100)
    public String getLmpPreco() {
        return this.lmpPreco;
    }
    
    public void setLmpPreco(String lmpPreco) {
        this.lmpPreco = lmpPreco;
    }

    
    @Column(name="lmp_categoria", nullable=false, length=50)
    public String getLmpCategoria() {
        return this.lmpCategoria;
    }
    
    public void setLmpCategoria(String lmpCategoria) {
        this.lmpCategoria = lmpCategoria;
    }

    
    @Column(name="lmp_tamanho", length=1)
    public String getLmpTamanho() {
        return this.lmpTamanho;
    }
    
    public void setLmpTamanho(String lmpTamanho) {
        this.lmpTamanho = lmpTamanho;
    }

    
    @Column(name="lmp_ativo", nullable=false, length=2)
    public String getLmpAtivo() {
        return this.lmpAtivo;
    }
    
    public void setLmpAtivo(String lmpAtivo) {
        this.lmpAtivo = lmpAtivo;
    }




}


