package bean;
// Generated 13/10/2025 22:36:20 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LmpUsuarios generated by hbm2java
 */
@Entity
@Table(name="lmp_usuarios"
    ,catalog="db_laura_peixoto"
)
public class LmpUsuarios  implements java.io.Serializable {


     private int lmpIdCodigo;
     private String lmpNome;
     private String lmpApelido;
     private String lmpCpf;
     private String lmpSenha;
     private Date lmpDataNascimento;
     private String lmpNivel;
     private String lmpAtivo;

    public LmpUsuarios() {
    }

	
    public LmpUsuarios(int lmpIdCodigo, String lmpNome, String lmpCpf, String lmpNivel, String lmpAtivo) {
        this.lmpIdCodigo = lmpIdCodigo;
        this.lmpNome = lmpNome;
        this.lmpCpf = lmpCpf;
        this.lmpNivel = lmpNivel;
        this.lmpAtivo = lmpAtivo;
    }
    public LmpUsuarios(int lmpIdCodigo, String lmpNome, String lmpApelido, String lmpCpf, String lmpSenha, Date lmpDataNascimento, String lmpNivel, String lmpAtivo) {
       this.lmpIdCodigo = lmpIdCodigo;
       this.lmpNome = lmpNome;
       this.lmpApelido = lmpApelido;
       this.lmpCpf = lmpCpf;
       this.lmpSenha = lmpSenha;
       this.lmpDataNascimento = lmpDataNascimento;
       this.lmpNivel = lmpNivel;
       this.lmpAtivo = lmpAtivo;
    }
   
     @Id 

    
    @Column(name="lmp_idCodigo", unique=true, nullable=false)
    public int getLmpIdCodigo() {
        return this.lmpIdCodigo;
    }
    
    public void setLmpIdCodigo(int lmpIdCodigo) {
        this.lmpIdCodigo = lmpIdCodigo;
    }

    
    @Column(name="lmp_nome", nullable=false, length=100)
    public String getLmpNome() {
        return this.lmpNome;
    }
    
    public void setLmpNome(String lmpNome) {
        this.lmpNome = lmpNome;
    }

    
    @Column(name="lmp_apelido", length=100)
    public String getLmpApelido() {
        return this.lmpApelido;
    }
    
    public void setLmpApelido(String lmpApelido) {
        this.lmpApelido = lmpApelido;
    }

    
    @Column(name="lmp_cpf", nullable=false, length=14)
    public String getLmpCpf() {
        return this.lmpCpf;
    }
    
    public void setLmpCpf(String lmpCpf) {
        this.lmpCpf = lmpCpf;
    }

    
    @Column(name="lmp_senha", length=50)
    public String getLmpSenha() {
        return this.lmpSenha;
    }
    
    public void setLmpSenha(String lmpSenha) {
        this.lmpSenha = lmpSenha;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="lmp_dataNascimento", length=10)
    public Date getLmpDataNascimento() {
        return this.lmpDataNascimento;
    }
    
    public void setLmpDataNascimento(Date lmpDataNascimento) {
        this.lmpDataNascimento = lmpDataNascimento;
    }

    
    @Column(name="lmp_nivel", nullable=false, length=30)
    public String getLmpNivel() {
        return this.lmpNivel;
    }
    
    public void setLmpNivel(String lmpNivel) {
        this.lmpNivel = lmpNivel;
    }

    
    @Column(name="lmp_ativo", nullable=false, length=1)
    public String getLmpAtivo() {
        return this.lmpAtivo;
    }
    
    public void setLmpAtivo(String lmpAtivo) {
        this.lmpAtivo = lmpAtivo;
    }




}


