package bean;
// Generated 13/10/2025 22:36:20 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LmpVendas generated by hbm2java
 */
@Entity
@Table(name = "lmp_vendas", catalog = "db_laura_peixoto"
)
public class LmpVendas implements java.io.Serializable {

    private int lmpIdnumeroVenda;
    private String lmpCodigo;
    private Date lmpDataVenda;
    private String lmpValorTotal;
    private String lmpFormaPagamento;
    private String lmpStatus;
    private String lmpEnviado;
    private LmpClientes lmpClientes;
    private LmpFuncionarios lmpFuncionarios;

    public LmpVendas() {
    }

    public LmpVendas(int lmpIdnumeroVenda, String lmpValorTotal, String lmpFormaPagamento, String lmpStatus, LmpClientes lmpClientes, LmpFuncionarios lmpFuncionarios) {
        this.lmpIdnumeroVenda = lmpIdnumeroVenda;
        this.lmpValorTotal = lmpValorTotal;
        this.lmpFormaPagamento = lmpFormaPagamento;
        this.lmpStatus = lmpStatus;
        this.lmpClientes = lmpClientes;
        this.lmpFuncionarios = lmpFuncionarios;
    }

    public LmpVendas(int lmpIdnumeroVenda, String lmpCodigo, Date lmpDataVenda, String lmpValorTotal, String lmpFormaPagamento, String lmpStatus, String lmpEnviado, LmpClientes lmpClientes, LmpFuncionarios lmpFuncionarios, Set lmpVendasItenses) {
        this.lmpIdnumeroVenda = lmpIdnumeroVenda;
        this.lmpCodigo = lmpCodigo;
        this.lmpDataVenda = lmpDataVenda;
        this.lmpValorTotal = lmpValorTotal;
        this.lmpFormaPagamento = lmpFormaPagamento;
        this.lmpStatus = lmpStatus;
        this.lmpEnviado = lmpEnviado;
        this.lmpClientes = lmpClientes;
        this.lmpFuncionarios = lmpFuncionarios;
    }

    @Id

    @Column(name = "lmp_idnumeroVenda", unique = true, nullable = false)
    public int getLmpIdnumeroVenda() {
        return this.lmpIdnumeroVenda;
    }

    public void setLmpIdnumeroVenda(int lmpIdnumeroVenda) {
        this.lmpIdnumeroVenda = lmpIdnumeroVenda;
    }

    @Column(name = "lmp_codigo", length = 15)
    public String getLmpCodigo() {
        return this.lmpCodigo;
    }

    public void setLmpCodigo(String lmpCodigo) {
        this.lmpCodigo = lmpCodigo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "lmp_dataVenda", length = 10)
    public Date getLmpDataVenda() {
        return this.lmpDataVenda;
    }

    public void setLmpDataVenda(Date lmpDataVenda) {
        this.lmpDataVenda = lmpDataVenda;
    }

    @Column(name = "lmp_valorTotal", nullable = false, length = 30)
    public String getLmpValorTotal() {
        return this.lmpValorTotal;
    }

    public void setLmpValorTotal(String lmpValorTotal) {
        this.lmpValorTotal = lmpValorTotal;
    }

    @Column(name = "lmp_formaPagamento", nullable = false, length = 40)
    public String getLmpFormaPagamento() {
        return this.lmpFormaPagamento;
    }

    public void setLmpFormaPagamento(String lmpFormaPagamento) {
        this.lmpFormaPagamento = lmpFormaPagamento;
    }

    @Column(name = "lmp_status", nullable = false, length = 20)
    public String getLmpStatus() {
        return this.lmpStatus;
    }

    public void setLmpStatus(String lmpStatus) {
        this.lmpStatus = lmpStatus;
    }

    @Column(name = "lmp_Enviado", length = 3)
    public String getLmpEnviado() {
        return this.lmpEnviado;
    }

    public void setLmpEnviado(String lmpEnviado) {
        this.lmpEnviado = lmpEnviado;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "lmp_clientes")
    public LmpClientes getLmpClientes() {
        return this.lmpClientes;
    }

    public void setLmpClientes(LmpClientes lmpClientes) {
        this.lmpClientes = lmpClientes;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "lmp_funcionarios")
    public LmpFuncionarios getLmpFuncionarios() {
        return this.lmpFuncionarios;
    }

    public void setLmpFuncionarios(LmpFuncionarios lmpFuncionarios) {
        this.lmpFuncionarios = lmpFuncionarios;
    }

}
