package bean;
// Generated 13/10/2025 22:36:20 by Hibernate Tools 4.3.1



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LmpVendasItens generated by hbm2java
 */
@Entity
@Table(name="lmp_vendasitens"
    ,catalog="db_laura_peixoto"
)
public class LmpVendasItens  implements java.io.Serializable {


     private int lmpIdItemVendido;
     private LmpProduto lmpProduto;
     private LmpVendas lmpVendas;
     private int lmpQuantidade;
     private double lmpPrecoUnitario;
     private double lmpDesconto;
     private double lmpValorTotalItem;


    public LmpVendasItens() {
    }

	
    public LmpVendasItens(int lmpIdItemVendido, int lmpQuantidade, double lmpPrecoUnitario, double lmpDesconto, double lmpValorTotalItem, LmpVendas lmpVendas) {
        this.lmpIdItemVendido = lmpIdItemVendido;
        this.lmpQuantidade = lmpQuantidade;
        this.lmpPrecoUnitario = lmpPrecoUnitario;
        this.lmpDesconto = lmpDesconto;
        this.lmpValorTotalItem = lmpValorTotalItem;
        this.lmpVendas = lmpVendas;
    }
    public LmpVendasItens(int lmpIdItemVendido, LmpProduto lmpProduto, LmpVendas lmpVendas, int lmpQuantidade, double lmpPrecoUnitario, double lmpDesconto, double lmpValorTotalItem) {
       this.lmpIdItemVendido = lmpIdItemVendido;
       this.lmpProduto = lmpProduto;
       this.lmpVendas = lmpVendas;
       this.lmpQuantidade = lmpQuantidade;
       this.lmpPrecoUnitario = lmpPrecoUnitario;
       this.lmpDesconto = lmpDesconto;
       this.lmpValorTotalItem = lmpValorTotalItem;
    }
   
     @Id 

    
    @Column(name="lmp_idItemVendido", unique=true, nullable=false)
    public int getLmpIdItemVendido() {
        return this.lmpIdItemVendido;
    }
    
    public void setLmpIdItemVendido(int lmpIdItemVendido) {
        this.lmpIdItemVendido = lmpIdItemVendido;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="lmp_idCodigoProduto")
    public LmpProduto getLmpProduto() {
        return this.lmpProduto;
    }
    
    public void setLmpProduto(LmpProduto lmpProduto) {
        this.lmpProduto = lmpProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="lmp_idnumeroVenda")
    public LmpVendas getLmpVendas() {
        return this.lmpVendas;
    }
    
    public void setLmpVendas(LmpVendas lmpVendas) {
        this.lmpVendas = lmpVendas;
    }

    
    @Column(name="lmp_quantidade", nullable=false)
    public int getLmpQuantidade() {
        return this.lmpQuantidade;
    }
    
    public void setLmpQuantidade(int lmpQuantidade) {
        this.lmpQuantidade = lmpQuantidade;
    }

    
    @Column(name="lmp_precoUnitario", nullable=false, precision=10)
    public double getLmpPrecoUnitario() {
        return this.lmpPrecoUnitario;
    }
    
    public void setLmpPrecoUnitario(double lmpPrecoUnitario) {
        this.lmpPrecoUnitario = lmpPrecoUnitario;
    }

    
    @Column(name="lmp_desconto", nullable=false, precision=10)
    public double getLmpDesconto() {
        return this.lmpDesconto;
    }
    
    public void setLmpDesconto(double lmpDesconto) {
        this.lmpDesconto = lmpDesconto;
    }

    
    @Column(name="lmp_valorTotalItem", nullable=false, precision=10)
    public double getLmpValorTotalItem() {
        return this.lmpValorTotalItem;
    }
    
    public void setLmpValorTotalItem(double lmpValorTotalItem) {
        this.lmpValorTotalItem = lmpValorTotalItem;
    }

 


}


